"use client";

import { createContext, useContext, useEffect, useMemo, useState } from "react";

export const languageOptions = [
  { value: "en", label: "English" },
  { value: "vi", label: "Tiếng Việt" },
  { value: "ja", label: "日本語" },
  { value: "ko", label: "한국어" },
  { value: "zh", label: "中文" },
  { value: "es", label: "Español" },
  { value: "fr", label: "Français" },
  { value: "de", label: "Deutsch" },
] as const;

export type Language = (typeof languageOptions)[number]["value"];
type TranslationKey = keyof typeof translations.en;

const translations = {
  en: {
    settings: "Settings", timerMinutes: "Timer (minutes)", pomodoro: "Pomodoro", shortBreak: "Short Break", longBreak: "Long Break", autoStart: "Auto Start", autoStartBreaks: "Auto-start breaks", autoStartPomodoros: "Auto-start pomodoros", alarmSound: "Alarm Sound", test: "Test", cancel: "Cancel", saveChanges: "Save changes", language: "Language", focusTasks: "Focus Tasks", trackToday: "Track what you're working on today", addTask: "Add New Task", taskPlaceholder: "What are you working on?", save: "Save", studyCalendar: "Study calendar", roadmap: "Study roadmap", focusTime: "Focus time", start: "START", pause: "PAUSE", resetTimer: "Reset Timer", studyStreak: "Study streak", studiedTotal: "studied in total", daysToMilestone: "days to your next milestone", selectedDay: "Selected day", completePomodoro: "Complete a Pomodoro to record study time.", studyRoadmap: "Study roadmap", roadmapDescription: "Turn a big goal into a clear plan for every day.", newGoal: "New goal", goalPrompt: "What do you want to achieve?", days: "Days", dailyFocus: "Daily focus", studyNotes: "Study notes", addFocus: "Add today's focus", focusPlaceholder: "What will you complete today?", notesPlaceholder: "What did you learn or finish?", createFirstGoal: "Create your first goal to plan what you will study each day.", toNextMilestone: "to your next milestone", syncing: "Syncing history...", loading: "Loading...", previousMonth: "Previous month", nextMonth: "Next month", day: "day", dayPlural: "days", deleteGoal: "Delete goal",
  },
  vi: {
    settings: "Cài đặt", timerMinutes: "Thời gian (phút)", pomodoro: "Pomodoro", shortBreak: "Nghỉ ngắn", longBreak: "Nghỉ dài", autoStart: "Tự động bắt đầu", autoStartBreaks: "Tự động bắt đầu giờ nghỉ", autoStartPomodoros: "Tự động bắt đầu Pomodoro", alarmSound: "Âm báo", test: "Thử", cancel: "Hủy", saveChanges: "Lưu thay đổi", language: "Ngôn ngữ", focusTasks: "Nhiệm vụ tập trung", trackToday: "Theo dõi việc bạn đang làm hôm nay", addTask: "Thêm nhiệm vụ", taskPlaceholder: "Bạn đang làm gì?", save: "Lưu", studyCalendar: "Lịch học", roadmap: "Lộ trình học", focusTime: "Giờ tập trung", start: "BẮT ĐẦU", pause: "TẠM DỪNG", resetTimer: "Đặt lại", studyStreak: "Chuỗi học", studiedTotal: "đã học tổng cộng", daysToMilestone: "ngày nữa đến cột mốc", selectedDay: "Ngày đã chọn", completePomodoro: "Hoàn thành Pomodoro để ghi nhận thời gian học.", studyRoadmap: "Lộ trình học", roadmapDescription: "Biến mục tiêu lớn thành kế hoạch rõ ràng cho từng ngày.", newGoal: "Mục tiêu mới", goalPrompt: "Bạn muốn đạt được điều gì?", days: "Số ngày", dailyFocus: "Trọng tâm hôm nay", studyNotes: "Ghi chú học tập", addFocus: "Thêm nội dung hôm nay", focusPlaceholder: "Hôm nay bạn sẽ hoàn thành gì?", notesPlaceholder: "Bạn đã học hoặc hoàn thành gì?", createFirstGoal: "Tạo mục tiêu đầu tiên để lên kế hoạch học mỗi ngày.", toNextMilestone: "đến cột mốc tiếp theo", syncing: "Đang đồng bộ lịch sử...", loading: "Đang tải...", previousMonth: "Tháng trước", nextMonth: "Tháng sau", day: "ngày", dayPlural: "ngày", deleteGoal: "Xóa mục tiêu",
  },
  ja: { settings: "設定", timerMinutes: "タイマー（分）", pomodoro: "ポモドーロ", shortBreak: "短い休憩", longBreak: "長い休憩", autoStart: "自動開始", autoStartBreaks: "休憩を自動開始", autoStartPomodoros: "ポモドーロを自動開始", alarmSound: "アラーム音", test: "試聴", cancel: "キャンセル", saveChanges: "変更を保存", language: "言語", focusTasks: "集中タスク", trackToday: "今日の作業を記録", addTask: "タスクを追加", taskPlaceholder: "何に取り組んでいますか？", save: "保存", studyCalendar: "学習カレンダー", roadmap: "学習ロードマップ", focusTime: "集中モード", start: "開始", pause: "一時停止", resetTimer: "リセット", studyStreak: "学習ストリーク", studiedTotal: "合計学習時間", daysToMilestone: "次の目標までの日数", selectedDay: "選択した日", completePomodoro: "ポモドーロを完了すると学習時間が記録されます。", studyRoadmap: "学習ロードマップ", roadmapDescription: "大きな目標を毎日の計画に分けます。", newGoal: "新しい目標", goalPrompt: "何を達成したいですか？", days: "日数", dailyFocus: "今日の学習", studyNotes: "学習メモ", addFocus: "今日の内容を追加", focusPlaceholder: "今日何を終わらせますか？", notesPlaceholder: "何を学びましたか？", createFirstGoal: "最初の目標を作って毎日の計画を立てましょう。", toNextMilestone: "次の目標まで", syncing: "履歴を同期中...", loading: "読み込み中...", previousMonth: "前月", nextMonth: "翌月", day: "日", dayPlural: "日", deleteGoal: "目標を削除" },
  ko: { settings: "설정", timerMinutes: "타이머 (분)", pomodoro: "뽀모도로", shortBreak: "짧은 휴식", longBreak: "긴 휴식", autoStart: "자동 시작", autoStartBreaks: "휴식 자동 시작", autoStartPomodoros: "뽀모도로 자동 시작", alarmSound: "알람 소리", test: "테스트", cancel: "취소", saveChanges: "변경 저장", language: "언어", focusTasks: "집중 작업", trackToday: "오늘 할 일을 기록하세요", addTask: "작업 추가", taskPlaceholder: "무엇을 하고 있나요?", save: "저장", studyCalendar: "학습 캘린더", roadmap: "학습 로드맵", focusTime: "집중 모드", start: "시작", pause: "일시정지", resetTimer: "초기화", studyStreak: "학습 연속 기록", studiedTotal: "총 학습 시간", daysToMilestone: "다음 목표까지", selectedDay: "선택한 날짜", completePomodoro: "뽀모도로를 완료하면 학습 시간이 기록됩니다.", studyRoadmap: "학습 로드맵", roadmapDescription: "큰 목표를 매일의 계획으로 나눠보세요.", newGoal: "새 목표", goalPrompt: "무엇을 이루고 싶나요?", days: "일수", dailyFocus: "오늘의 학습", studyNotes: "학습 메모", addFocus: "오늘의 내용 추가", focusPlaceholder: "오늘 무엇을 완료할까요?", notesPlaceholder: "무엇을 배웠나요?", createFirstGoal: "첫 목표를 만들어 매일의 계획을 세워보세요.", toNextMilestone: "다음 목표까지", syncing: "기록 동기화 중...", loading: "불러오는 중...", previousMonth: "이전 달", nextMonth: "다음 달", day: "일", dayPlural: "일", deleteGoal: "목표 삭제" },
  zh: { settings: "设置", timerMinutes: "计时器（分钟）", pomodoro: "番茄钟", shortBreak: "短休息", longBreak: "长休息", autoStart: "自动开始", autoStartBreaks: "自动开始休息", autoStartPomodoros: "自动开始番茄钟", alarmSound: "提示音", test: "试听", cancel: "取消", saveChanges: "保存更改", language: "语言", focusTasks: "专注任务", trackToday: "记录今天的工作", addTask: "添加任务", taskPlaceholder: "你正在做什么？", save: "保存", studyCalendar: "学习日历", roadmap: "学习路线", focusTime: "专注模式", start: "开始", pause: "暂停", resetTimer: "重置", studyStreak: "学习连续记录", studiedTotal: "累计学习", daysToMilestone: "天到下一个里程碑", selectedDay: "选择的日期", completePomodoro: "完成一个番茄钟即可记录学习时间。", studyRoadmap: "学习路线", roadmapDescription: "把大目标变成每天清晰的计划。", newGoal: "新目标", goalPrompt: "你想实现什么？", days: "天数", dailyFocus: "今日重点", studyNotes: "学习笔记", addFocus: "添加今日内容", focusPlaceholder: "今天要完成什么？", notesPlaceholder: "你学到了什么？", createFirstGoal: "创建第一个目标，规划每天的学习。", toNextMilestone: "天到下一个目标", syncing: "正在同步记录...", loading: "加载中...", previousMonth: "上个月", nextMonth: "下个月", day: "天", dayPlural: "天", deleteGoal: "删除目标" },
  es: { settings: "Ajustes", timerMinutes: "Temporizador (minutos)", pomodoro: "Pomodoro", shortBreak: "Descanso corto", longBreak: "Descanso largo", autoStart: "Inicio automático", autoStartBreaks: "Iniciar descansos automáticamente", autoStartPomodoros: "Iniciar pomodoros automáticamente", alarmSound: "Sonido de alarma", test: "Probar", cancel: "Cancelar", saveChanges: "Guardar cambios", language: "Idioma", focusTasks: "Tareas de enfoque", trackToday: "Registra lo que haces hoy", addTask: "Añadir tarea", taskPlaceholder: "¿En qué estás trabajando?", save: "Guardar", studyCalendar: "Calendario de estudio", roadmap: "Ruta de estudio", focusTime: "Modo enfoque", start: "INICIAR", pause: "PAUSA", resetTimer: "Restablecer", studyStreak: "Racha de estudio", studiedTotal: "estudiado en total", daysToMilestone: "días para el próximo objetivo", selectedDay: "Día seleccionado", completePomodoro: "Completa un Pomodoro para registrar el tiempo de estudio.", studyRoadmap: "Ruta de estudio", roadmapDescription: "Convierte un gran objetivo en un plan diario claro.", newGoal: "Nuevo objetivo", goalPrompt: "¿Qué quieres lograr?", days: "Días", dailyFocus: "Enfoque diario", studyNotes: "Notas de estudio", addFocus: "Añadir enfoque de hoy", focusPlaceholder: "¿Qué completarás hoy?", notesPlaceholder: "¿Qué aprendiste o terminaste?", createFirstGoal: "Crea tu primer objetivo para planificar cada día.", toNextMilestone: "para el próximo objetivo", syncing: "Sincronizando historial...", loading: "Cargando...", previousMonth: "Mes anterior", nextMonth: "Mes siguiente", day: "día", dayPlural: "días", deleteGoal: "Eliminar objetivo" },
  fr: { settings: "Réglages", timerMinutes: "Minuteur (minutes)", pomodoro: "Pomodoro", shortBreak: "Pause courte", longBreak: "Pause longue", autoStart: "Démarrage automatique", autoStartBreaks: "Démarrer les pauses automatiquement", autoStartPomodoros: "Démarrer les pomodoros automatiquement", alarmSound: "Sonnerie", test: "Tester", cancel: "Annuler", saveChanges: "Enregistrer", language: "Langue", focusTasks: "Tâches prioritaires", trackToday: "Suivez votre travail du jour", addTask: "Ajouter une tâche", taskPlaceholder: "Sur quoi travaillez-vous ?", save: "Enregistrer", studyCalendar: "Calendrier d'étude", roadmap: "Parcours d'étude", focusTime: "Mode concentration", start: "DÉMARRER", pause: "PAUSE", resetTimer: "Réinitialiser", studyStreak: "Série d'étude", studiedTotal: "étudiées au total", daysToMilestone: "jours avant le prochain objectif", selectedDay: "Jour sélectionné", completePomodoro: "Terminez un Pomodoro pour enregistrer votre temps d'étude.", studyRoadmap: "Parcours d'étude", roadmapDescription: "Transformez un grand objectif en plan quotidien.", newGoal: "Nouvel objectif", goalPrompt: "Que voulez-vous accomplir ?", days: "Jours", dailyFocus: "Objectif du jour", studyNotes: "Notes d'étude", addFocus: "Ajouter le travail du jour", focusPlaceholder: "Que terminerez-vous aujourd'hui ?", notesPlaceholder: "Qu'avez-vous appris ou terminé ?", createFirstGoal: "Créez votre premier objectif et planifiez chaque jour.", toNextMilestone: "avant le prochain objectif", syncing: "Synchronisation...", loading: "Chargement...", previousMonth: "Mois précédent", nextMonth: "Mois suivant", day: "jour", dayPlural: "jours", deleteGoal: "Supprimer l'objectif" },
  de: { settings: "Einstellungen", timerMinutes: "Timer (Minuten)", pomodoro: "Pomodoro", shortBreak: "Kurze Pause", longBreak: "Lange Pause", autoStart: "Automatischer Start", autoStartBreaks: "Pausen automatisch starten", autoStartPomodoros: "Pomodoros automatisch starten", alarmSound: "Alarmsound", test: "Testen", cancel: "Abbrechen", saveChanges: "Änderungen speichern", language: "Sprache", focusTasks: "Fokusaufgaben", trackToday: "Verfolge deine Aufgaben heute", addTask: "Aufgabe hinzufügen", taskPlaceholder: "Woran arbeitest du?", save: "Speichern", studyCalendar: "Lernkalender", roadmap: "Lernplan", focusTime: "Fokusmodus", start: "START", pause: "PAUSE", resetTimer: "Zurücksetzen", studyStreak: "Lernserie", studiedTotal: "insgesamt gelernt", daysToMilestone: "Tage bis zum nächsten Ziel", selectedDay: "Ausgewählter Tag", completePomodoro: "Schließe ein Pomodoro ab, um die Lernzeit zu speichern.", studyRoadmap: "Lernplan", roadmapDescription: "Mache aus einem großen Ziel einen klaren Tagesplan.", newGoal: "Neues Ziel", goalPrompt: "Was möchtest du erreichen?", days: "Tage", dailyFocus: "Tagesfokus", studyNotes: "Lernnotizen", addFocus: "Heutiges Ziel hinzufügen", focusPlaceholder: "Was wirst du heute erledigen?", notesPlaceholder: "Was hast du gelernt oder erledigt?", createFirstGoal: "Erstelle dein erstes Ziel und plane jeden Tag.", toNextMilestone: "bis zum nächsten Ziel", syncing: "Verlauf wird synchronisiert...", loading: "Wird geladen...", previousMonth: "Vorheriger Monat", nextMonth: "Nächster Monat", day: "Tag", dayPlural: "Tage", deleteGoal: "Ziel löschen" },
} satisfies Record<Language, Record<string, string>>;

type LanguageContextValue = { language: Language; setLanguage: (language: Language) => void; t: (key: TranslationKey) => string };
const LanguageContext = createContext<LanguageContextValue | null>(null);

const browserLanguage = (): Language => {
  if (typeof navigator === "undefined") return "en";
  const code = navigator.language.slice(0, 2) as Language;
  return languageOptions.some((option) => option.value === code) ? code : "en";
};

export function LanguageProvider({ children }: { children: React.ReactNode }) {
  const [language, setLanguageState] = useState<Language>("en");
  useEffect(() => {
    const saved = localStorage.getItem("promodo-language") as Language | null;
    setLanguageState(saved && languageOptions.some((option) => option.value === saved) ? saved : browserLanguage());
  }, []);
  const setLanguage = (nextLanguage: Language) => { setLanguageState(nextLanguage); localStorage.setItem("promodo-language", nextLanguage); };
  const value = useMemo(() => ({ language, setLanguage, t: (key: TranslationKey) => translations[language][key] }), [language]);
  return <LanguageContext.Provider value={value}>{children}</LanguageContext.Provider>;
}

export function useLanguage() {
  const context = useContext(LanguageContext);
  if (!context) throw new Error("useLanguage must be used inside LanguageProvider");
  return context;
}